programs = {
    "♻️ (apt)  update debian packages": "apt-get clean && apt-get update && apt-get dist-upgrade -y && apt-get full-upgrade -y && apt-get autoremove -y",
    "(apt)  flatpak with flathub": "sudo apt install -y flatpak && flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "(apt)(snap)  snapd and snap store gui\n": "sudo apt install -y snapd && sudo snap install snapd && sudo snap install snap-store",
    "♻️ (flatpak)  update flatpak packages ": "sudo flatpak update -y",
    "♻️ (snap)  update snap packages": "sudo snap refresh",
    "(apt)  gedit and gedit's plugins": "apt install -y gedit && apt install -y gedit-plugins",
    "(apt)  neofetch": "apt install -y neofetch",
    "(apt)  lm-sensors": "apt install -y lm-sensors",
    "(apt)  psensor (gui)": "apt install -y psensor",
    "(apt)  acpi (battery percentage laptop (terminal command))": "apt install -y acpi",
    "(apt)  openbox": "apt install -y openbox",
    "(apt)  tree": "apt install -y tree",
    "(apt)  fish": "apt install -y fish",
    "(apt)  flatpak-plugin-gnome": "sudo apt install -y gnome-software-plugin-flatpak",
    "(apt)  flatpak-plugin-KDE_Plasma": "sudo apt install -y plasma-discover-backend-flatpak",
    "(flatpak)  discord": "flatpak install -y flathub com.discordapp.Discord",
    "(flatpak)  chromium": "flatpak install -y flathub org.chromium.Chromium",
    "(flatpak)  Intellij Community": "flatpak install -y com.jetbrains.IntelliJ-IDEA-Community",
    "(flatpak)  Android Studio": "flatpak install -y com.google.AndroidStudio",
    "(flatpak)  Visual Studio Code": "flatpak install -y com.visualstudio.code",
    "(flatpak)  spotify": "flatpak install -y flathub com.spotify.Client",
    "(flatpak)  steam": "flatpak install -y flathub com.valvesoftware.Steam",
    "(flatpak)  telegram": "flatpak install -y flathub org.telegram.desktop",
    "(flatpak)  0ad": "flatpak install -y com.play0ad.zeroad",
    "(apt)  KVM \"Kernel Virtual Machine\" Desktop use 💻": "sudo apt install -y qemu-system libvirt-daemon-system",
    "(apt)  KVM \"Kernel Virtual Machine\" Server use 💾": "sudo apt install -y --no-install-recommends qemu-system libvirt-clients libvirt-daemon-system",
    "(snap) Microsoft Teams": "sudo snap install teams-for-linux"

}

